version: 0.0


os: linux


files:
  - source: index.html
    destination: /var/www/html/
  - source: mydir
    destination: /var/www/html/


permissions:
  - object: /var/www/html/index.html
    owner: root
    group: root
    mode: 644
    type:
      - file


hooks:
  ApplicationStop:
    - location: scripts/stop.sh

  ApplicationStart:
    - location: scripts/start.sh

  ValidateService:
    - location: scripts/validate.sh


